### ISSUE TITLE
1.12.2 Crash with AE2 Unofficial Extended Life

### ISSUE THREAD

**Issue by mczph** [Ecdcaeb/Redirectionor#3]
https://mclo.gs/mfyMv3S

**Comment by aking4125** [comment]
Can confirm the same issue with redirectionor-1.12.2-1.8.8-1.1 - https://mclo.gs/Tfm6aLU

Downgrading to redirectionor-1.12.2-1.8.8 solves the issue and the client starts normally.

**Comment by Ecdcaeb** [comment]
this bug will not be fixed until Saturday.

**Comment by Ecdcaeb** [comment]
something strange
![image](https://github.com/Ecdcaeb/Redirectionor/assets/107909747/6b85b2c8-3b2d-47d3-a3b5-4b2deec73c6e)

**Comment by Ecdcaeb** [comment]
Crash with AE2 Unofficial Extended Life
But I don't know why.I can't crash it......
I will release this jar soon...
](https://github.com/Ecdcaeb/Redirectionor/releases/tag/ae2uc)
