### ISSUE TITLE
1.12.2 Various mods break

### ISSUE THREAD

**Issue by Mysticpasta1** [Ecdcaeb/Redirectionor#4]
Tested with my 1000 mod modpack here -> https://www.curseforge.com/minecraft/modpacks/mystics-monstrosity
hatchery, mouse tweaks, ae2 extended life (#3), and multiple other are crashing in various ways

ae2 crash is the same as in #3

[crash-2023-08-31_19.30.24-client.txt](https://github.com/Ecdcaeb/Redirectionor/files/12495535/crash-2023-08-31_19.30.24-client.txt)
[crash-2023-08-31_19.54.09-client.txt](https://github.com/Ecdcaeb/Redirectionor/files/12495536/crash-2023-08-31_19.54.09-client.txt)
[crash-2023-09-01_02.03.11-client.txt](https://github.com/Ecdcaeb/Redirectionor/files/12495537/crash-2023-09-01_02.03.11-client.txt)
[crash-2023-08-31_20.04.57-client.txt](https://github.com/Ecdcaeb/Redirectionor/files/12495538/crash-2023-08-31_20.04.57-client.txt)

**Comment by Ecdcaeb** [comment]
this bug will not be fixed until Saturday.

**Comment by Ecdcaeb** [comment]
[latest.log](https://github.com/Ecdcaeb/Redirectionor/files/12532823/latest.log)
crash,this mod pack.(no Redirectionor)

**Comment by Ecdcaeb** [comment]
19.8.5

**Comment by Mysticpasta1** [comment]
seems like an internet issue but idk

**Comment by Mysticpasta1** [comment]
also be sure to load with 26GB

**Comment by Ecdcaeb** [comment]
This crash may be related to the complex environment of the modpack, and Hileb's separate testing of each mod did not cause their crash.

**Comment by Ecdcaeb** [comment]
this modpack require online?

**Comment by Ecdcaeb** [comment]
Hileb could nothing with his 8GB RAM......(22+?)
Sorry......

**Comment by Ecdcaeb** [comment]
oh!
I tested 1.1 and it crashed with solarenergy.But i had fixed it before i handled this issue inadvertently.
1.2 have been available.
