### ISSUE TITLE
1.7.10 Crash with OptiFine

### ISSUE THREAD

**Issue by GedeonGrays** [Ecdcaeb/Redirectionor#5]
_Hello o/_

When you click on some buttons in the graphics settings, it crashes. 
The sequence of actions to reproduce the crash: **Options -> Video Settings -> GUI Scale / Chunk Loading / Dynamic Lights / Dynamic FOV** etc.

**Redirectionor Version:** 1.1
**OptiFine Version:** HD_U_E7
**Forge Version:** 10.13.4.1614

**Crash report:** https://pastebin.com/cri1UwSY

**Comment by GedeonGrays** [comment]
No problem, I won't rush you, and I'll wait as long as it takes.

**Comment by Ecdcaeb** [comment]
hoping not late....
1.7.10-1.2 is available!
no crash any more.
Moreover,config/redirectionor_cfg.json is available too.It will be generoused automatically!You can adjust it to avoid some crash too![https://github.com/Ecdcaeb/Redirectionor/wiki/Config_English](urlhttps://github.com/Ecdcaeb/Redirectionor/wiki/Config_English)

**Comment by GedeonGrays** [comment]
Yeah, it's cool and looks like it's fixed and working great👍

A little bit off-topic: could you suggest how best to estimate the beneficial impact (reduced RAM or CPU time utilization, etc.) of Redirectionor? I just want to understand the usefulness specifically on my average modpack🤔

**Comment by Ecdcaeb** [comment]
I don't konw,I have not test the mod on any modpack successfully.
For example,GTNH,I cound't run it with my computer although Redirectionor was added.(How obsolete my computer is!)
Moreover, I am not familiar with ModPack, so I have never thought of a suitable test object.
Perhaps you can recommend a few, or test yourself and publish the results.

**Comment by GedeonGrays** [comment]
> Perhaps you can recommend a few, or test yourself and publish the results. 

In my spare time, I'll do some thorough testing and report back. But I can't say when it will be done.

**Comment by Ecdcaeb** [comment]
thank you very much.

**Comment by GedeonGrays** [comment]
> In my spare time, I'll do some thorough testing and report back. But I can't say when it will be done.

The test was conducted a long time ago, but only now I could write a comment.

_**Note: I do not claim to be an expert and cannot guarantee the accuracy of measurements or correct interpretation of results.**_

The testing was done on a modpack of 170 mods without any JVM arguments. The following tools were used: VisualVM, JMC and MAT.

In general, regardless of the tools used, I did not manage to get a significant difference in performance and memory consumption that could not be written off as a margin of error. 

It's entirely possible that this is too situational a mod, and hopefully it will really help someone, but apparently not for my modpack. If anything changes on my end, I'll be sure to edit this comment.

**Comment by Ecdcaeb** [comment]
In my testing as well, `values()` usually doesn't cost a log, even though it trivially copies the pointer array. I don't know how potatoes achieve such great results. This may depend on whether there are expensive shit code mods in the modpack.

**Comment by GedeonGrays** [comment]
> In my testing as well, `values()` usually doesn't cost a lot, even though it trivially copies the pointer array. I don't know how Potatoes achieve such great results. This may depend on whether there are expensive shit code mods in the modpack.

You're probably right. In any case, if the mod doesn't make things worse, and even helps someone in certain cases - why not ¯\_(ツ)_/¯
