### ISSUE TITLE
与 Sampler 安装时崩溃。

### ISSUE THREAD

**Issue by KasumiNova** [Ecdcaeb/Redirectionor#6]
崩溃报告：https://mclo.gs/LyxfCVw
模组 MCMOD 地址：https://www.mcmod.cn/class/4201.html
模组闭源且混淆，不清楚能够修复。
目前仅发现与此模组一起安装时会崩溃，其他模组尚未发现问题。

**Comment by Ecdcaeb** [comment]
redirectionor (redirectionor-1.12.2-1.8.8.jar)
your mod is out of date,try 1.12.2-1.8.8-1.2

**Comment by Ecdcaeb** [comment]
![image](https://github.com/Ecdcaeb/Redirectionor/assets/107909747/1e6e3fa7-9797-4c8e-bfb1-6459ed0e3f31)
run successfully!
